"""Database connection and the single writer that owns it.

One writer, enforced rather than assumed (PLAN §2.6). Writes are funnelled through a
single-threaded executor, so there is exactly one thread that may mutate the database and its
identity can be asserted. An `asyncio.Lock` preserves submission order on top of that, which
also gives the event log a stable total order.

SQLite runs in WAL mode: readers never block the writer, which is what lets the dashboard query
projections while a cycle is mid-flight.

Failure semantics: a failed unit of work rolls back its whole transaction — an event and the
projection it feeds are written together or not at all, so the log can never describe a state
the projections don't show.
"""

from __future__ import annotations

import asyncio
import threading
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import TypeVar

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import Connection, Engine, create_engine, event, inspect
from sqlalchemy.engine.interfaces import DBAPIConnection
from sqlalchemy.pool import StaticPool

from tradebot.core.clock import Clock, SystemClock
from tradebot.core.errors import SingleWriterViolationError
from tradebot.maintenance.backup import backup_destination, take_backup

T = TypeVar("T")

WRITER_THREAD_NAME = "tradebot-db-writer"
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


def create_database(path: Path | None) -> Engine:
    """Open (creating if needed) the database for one mode, at the head revision.

    Each mode uses its own file, so a paper ledger can never be read as a live one (PLAN §2.4).
    `None` gives an in-memory database for tests.
    """
    engine = open_database(path)
    if path is None:
        run_migrations(engine)
    else:
        run_migrations(engine, backup=backup_destination(path), mode=path.stem, clock=SystemClock())
    return engine


def open_database(path: Path | None) -> Engine:
    """Open the database **without** migrating it.

    Split out from `create_database` because taking a backup must never be the thing that upgrades
    a schema: an operator copying `live.db` before a release, to have a rollback point for exactly
    that release, would otherwise find the copy command had already performed the migration they
    were making the point *for* (spec §4.5). `tradebot maintenance` is the only caller.
    """
    if path is None:
        # An in-memory database lives *inside its connection*, so every pooled connection would
        # otherwise get its own empty schema. StaticPool keeps one connection for the process.
        engine = create_engine(
            "sqlite:///:memory:",
            future=True,
            poolclass=StaticPool,
            connect_args={"check_same_thread": False},
        )
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        engine = create_engine(
            f"sqlite:///{path}",
            future=True,
            # The writer runs on its own thread; readers on others. WAL makes that safe, and
            # serialization is enforced by `SingleWriter`, not by pysqlite's thread check.
            connect_args={"check_same_thread": False},
        )

    @event.listens_for(engine, "connect")
    def _configure(connection: DBAPIConnection, _record: object) -> None:
        cursor = connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA synchronous=FULL")  # an order must survive a power cut
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()

    return engine


def run_migrations(
    engine: Engine,
    *,
    backup: Path | None = None,
    mode: str = "",
    clock: Clock | None = None,
    take: Callable[..., object] = take_backup,
) -> None:
    """Bring the database to the head revision, copying it first if that will change anything.

    Alembic is the single source of schema truth from day one, including for a fresh database.
    `create_all` would work today and then leave the first schema change with no upgrade path —
    unacceptable for a database that holds financial records that cannot be recreated. For the
    same reason the upgrade is preceded by a backup whenever it will actually move the revision,
    and **a backup that cannot be taken stops the upgrade** (spec §4.5): a bad autogenerated
    migration against `live.db` is the most likely way this system ever loses records that cannot
    be recreated, and it is the one destructive act with no rollback point of its own.

    Every keyword defaults to "do exactly what this did before", so `backup=None` — the in-memory
    database the whole test suite runs on — skips the hook by construction rather than by a
    test-only branch. `take` is the only injected seam, so a test can starve the backup without a
    full disk.

    The migration runs on the engine's *own* connection: an in-memory database lives inside its
    connection, so opening a second one would migrate a different database. The revision check and
    the copy both complete **before** `engine.begin()` opens the migration transaction — `VACUUM
    INTO` cannot run inside one, and nesting them would deadlock a file database against itself.
    """
    config = Config(str(_PROJECT_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_PROJECT_ROOT / "migrations"))

    if backup is not None:
        revision = _revision_to_preserve(engine, config)
        if revision is not None:
            take(engine, backup, mode=mode, clock=clock or SystemClock(), revision=revision)

    with engine.begin() as connection:
        config.attributes["connection"] = connection
        command.upgrade(config, "head")


def _revision_to_preserve(engine: Engine, config: Config) -> str | None:
    """The revision a copy should be named for, or `None` when there is nothing to lose.

    Two conditions, both necessary. The upgrade must actually *move* the revision — a process
    starting against a database already at head is almost every start, and a copy on each one is a
    copy nobody reads. And the database must already hold something: a file this very call created
    has no rows to lose, and copying it would put the free-space guard between a fresh install and
    its first start, refusing to boot over a database that is empty by definition.

    A database holding tables but **no** `alembic_version` reads as `base` and is copied, not
    skipped. That is the fail-closed reading of an ambiguous file: it cannot be told apart from a
    real ledger whose version table was lost, and only one of the two possible mistakes is
    recoverable.
    """
    head = ScriptDirectory.from_config(config).get_current_head()
    with engine.connect() as connection:
        current = MigrationContext.configure(connection).get_current_revision()
        if current == head:
            return None
        if not inspect(connection).get_table_names():
            return None
    return current or "base"


class SingleWriter:
    """Serializes every write and guarantees exactly one writing thread."""

    def __init__(self, engine: Engine) -> None:
        self._engine = engine
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix=WRITER_THREAD_NAME)
        self._lock = asyncio.Lock()

    async def run(self, work: Callable[[Connection], T]) -> T:
        """Execute `work` in the writer thread inside one transaction."""
        async with self._lock:
            loop = asyncio.get_running_loop()
            return await loop.run_in_executor(self._executor, self._execute, work)

    def _execute(self, work: Callable[[Connection], T]) -> T:
        self._assert_writer_thread()
        with self._engine.begin() as connection:
            return work(connection)

    @staticmethod
    def _assert_writer_thread() -> None:
        name = threading.current_thread().name
        if not name.startswith(WRITER_THREAD_NAME):
            raise SingleWriterViolationError(f"database write attempted from thread {name!r}")

    def close(self) -> None:
        self._executor.shutdown(wait=True)
