"""The frozen, point-in-time input packet the panel sees. Its whole world (DESIGN §7.2).

The snapshot is serialized once, hashed, and stored; every seat prompt embeds the same packet.
That is what makes "this is what the panel saw" a checkable claim instead of a story, and what
lets a replayed decision be compared against the original.

The panel gets **no tool use and no retrieval**. Every number in here was computed by our own
code — asking a model what the price is invites a confident hallucination that executes before
anyone can verify it (DESIGN [L7]).
"""

from __future__ import annotations

from decimal import Decimal
from hashlib import blake2s

from tradebot.core.instrument import Instrument
from tradebot.core.market import Quote
from tradebot.core.schema import DomainModel, Money, UtcDatetime, canonical_json


class IndicatorReading(DomainModel):
    """One indicator value plus its deterministic verbalization.

    The text is generated by code and golden-tested, so the wording a seat reads cannot drift
    between runs and silently change the decision (DESIGN §6.3).
    """

    name: str
    timeframe: str
    value: Money
    text: str


class PositionView(DomainModel):
    """The normalized position slice the panel is allowed to see.

    Deliberately not the ledger: enough context to reason with, no ledger authority and no raw
    balances (DESIGN §6.5).
    """

    qty: Money
    unrealized_pnl_pct: Money
    held_cycles: int


class NewsItemView(DomainModel):
    """A news item as the panel sees it — data, never instructions.

    Headlines are attacker-visible input. The content is delimited in the prompt and the panel
    has no tools, so an injection can flip a marginal vote but can never size, route, or exceed
    risk limits on an order (DESIGN §8.3).
    """

    source: str
    title: str
    summary: str
    published_at: UtcDatetime
    observed_at: UtcDatetime
    relevance: Money


class InstrumentContext(DomainModel):
    """Everything the panel knows about one instrument this cycle."""

    instrument: Instrument
    quote: Quote
    candle_summaries: tuple[tuple[str, str], ...] = ()
    indicators: tuple[IndicatorReading, ...] = ()
    position: PositionView | None = None
    #: True when the venue cannot hold a protective stop for this instrument, so the position
    #: would be unguarded between cycles. Surfaced so the panel weighs it (DESIGN §6.7, R12).
    unprotected_position: bool = False

    def indicator(self, name: str, timeframe: str) -> IndicatorReading | None:
        return next(
            (i for i in self.indicators if i.name == name and i.timeframe == timeframe), None
        )


class BasketState(DomainModel):
    """How much of the basket's risk budget is already committed."""

    risk_budget_used_pct: Money = Decimal(0)
    recent_actions: tuple[str, ...] = ()


class ContextSnapshot(DomainModel):
    """A frozen decision context. Immutable by construction, hashable for replay."""

    snapshot_id: str
    basket_id: str
    as_of: UtcDatetime
    instruments: tuple[InstrumentContext, ...]
    news: tuple[NewsItemView, ...] = ()
    basket_state: BasketState = BasketState()
    actions_allowed: tuple[str, ...] = ("BUY", "SELL", "HOLD", "WAIT")
    note: str = "sizing is decided by risk management, not by the panel"

    @property
    def digest(self) -> str:
        """Content hash. Survives snapshot compaction, so replay stays verifiable forever."""
        return blake2s(canonical_json(self).encode(), digest_size=16).hexdigest()

    def context_for(self, instrument_key: str) -> InstrumentContext:
        found = next((i for i in self.instruments if i.instrument.key == instrument_key), None)
        if found is None:
            raise KeyError(f"{instrument_key} is not in snapshot {self.snapshot_id}")
        return found
