"""baseline: event log and projections

Revision ID: 0001
Revises:
Create Date: 2026-07-26 02:46:14.582672
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.persistence.schema

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cycles",
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("basket_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.Column("completed_at", tradebot.persistence.schema.UtcText(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("snapshot_digest", sa.String(length=64), nullable=True),
        sa.Column("cost_usd", tradebot.persistence.schema.DecimalText(), nullable=True),
        sa.PrimaryKeyConstraint("cycle_id"),
    )
    with op.batch_alter_table("cycles", schema=None) as batch_op:
        batch_op.create_index("ix_cycles_basket", ["basket_id"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_key", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("conviction", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("size_hint", sa.String(length=16), nullable=False),
        sa.Column("reasoning_summary", sa.Text(), nullable=True),
        sa.Column("dissent_json", sa.Text(), nullable=True),
        sa.Column("flags_json", sa.Text(), nullable=True),
        sa.Column("decided_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("cycle_id", "instrument_key"),
    )
    op.create_table(
        "events",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("ts", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("basket_id", sa.String(length=64), nullable=True),
        sa.Column("cycle_id", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("event_id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_aggregate", ["aggregate_id"], unique=False)
        batch_op.create_index("ix_events_cycle", ["cycle_id"], unique=False)
        batch_op.create_index("ix_events_type", ["type"], unique=False)

    op.create_table(
        "fills",
        sa.Column("fill_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_key", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("price", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("fee", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("fee_currency", sa.String(length=16), nullable=True),
        sa.Column("filled_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index("ix_fills_order", ["client_order_id"], unique=False)

    op.create_table(
        "orders",
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("basket_id", sa.String(length=64), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_key", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=24), nullable=False),
        sa.Column("qty", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("limit_price", tradebot.persistence.schema.DecimalText(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("venue_order_id", sa.String(length=64), nullable=True),
        sa.Column("filled_qty", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("avg_fill_price", tradebot.persistence.schema.DecimalText(), nullable=True),
        sa.Column("created_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.Column("updated_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("client_order_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("ix_orders_cycle", ["cycle_id"], unique=False)
        batch_op.create_index("ix_orders_state", ["state"], unique=False)

    op.create_table(
        "positions",
        sa.Column("instrument_key", sa.String(length=128), nullable=False),
        sa.Column("qty", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("avg_entry", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("realized_pnl", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("held_cycles", sa.Integer(), nullable=False),
        sa.Column("updated_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("instrument_key"),
    )
    op.create_table(
        "risk_events",
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("ts", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("action_taken", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refused.

    Downgrading past the baseline drops the `events` table, which is the audit trail and the
    only thing that can reconstruct what the system did with real money. Destroying it is a
    deliberate manual act (delete the database file), never something a migration does on the
    way to fixing something else (PLAN §3.3).
    """
    raise RuntimeError(
        "refusing to downgrade past the baseline: this would drop the append-only audit trail"
    )
