"""phase 2: protective legs, round trips, reconciliation, persisted risk state

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-26 13:32:55.737571

Autogenerated, then adjusted in three places that autogenerate cannot see:

* the new `orders` columns carry `server_default`s, because existing rows predate them and a
  `NOT NULL` column with no default cannot be added to a table that already has orders in it;
* `group_id` back-fills to the row's own `client_order_id`, which is exactly what the domain
  model means by "an entry is its own group";
* `positions.held_cycles` is replaced by `opened_at`. The counter lived in memory and reset on
  every restart, so a position held for days was reported to the panel as brand new; the holding
  period is now derived from `opened_at` and the cycle log, which a restart cannot forget.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import tradebot.persistence.schema  # custom column types render fully qualified

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "basket_status",
        sa.Column("basket_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("updated_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("basket_id"),
    )
    op.create_table(
        "reconciliations",
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("classification", sa.String(length=32), nullable=False),
        sa.Column("observed_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_seq"),
    )
    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.create_index("ix_reconciliations_class", ["classification"], unique=False)

    op.create_table(
        "risk_state",
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("kill_switch", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("high_water_mark", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("day_start_equity", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("day_started_on", sa.String(length=10), nullable=True),
        sa.Column("updated_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("scope"),
    )
    op.create_table(
        "round_trips",
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("basket_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_key", sa.String(length=128), nullable=False),
        sa.Column("qty", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("entry_price", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("exit_price", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("realized_pnl", tradebot.persistence.schema.DecimalText(), nullable=False),
        sa.Column("opened_at", tradebot.persistence.schema.UtcText(), nullable=True),
        sa.Column("closed_at", tradebot.persistence.schema.UtcText(), nullable=False),
        sa.PrimaryKeyConstraint("event_seq"),
    )
    with op.batch_alter_table("round_trips", schema=None) as batch_op:
        batch_op.create_index("ix_round_trips_instrument", ["instrument_key"], unique=False)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("role", sa.String(length=16), nullable=False, server_default="entry")
        )
        batch_op.add_column(
            sa.Column("group_id", sa.String(length=64), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("stop_price", tradebot.persistence.schema.DecimalText(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("expires_at", tradebot.persistence.schema.UtcText(), nullable=True)
        )
        batch_op.create_index("ix_orders_group", ["group_id"], unique=False)

    # Pre-Phase-2 orders were entries with no legs, so each is its own group.
    op.execute("UPDATE orders SET group_id = client_order_id WHERE group_id = ''")

    # `held_cycles` was a counter kept in memory and therefore reset by every restart. The
    # holding period is now derived from `opened_at` and the cycle log, which survives one.
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opened_at", tradebot.persistence.schema.UtcText()))
        batch_op.drop_column("held_cycles")


def downgrade() -> None:
    """Permitted: everything dropped here is reconstructable from the event log.

    `risk_state` and `basket_status` are current posture rather than derived tables, but every
    change to them also emitted a `KILL_SWITCH_CHANGED` or `BASKET_STATUS_CHANGED` event, so a
    downgrade loses the cache and not the fact. Unlike the baseline, this does not touch the
    audit trail itself.
    """
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("held_cycles", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.drop_column("opened_at")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_group")
        batch_op.drop_column("expires_at")
        batch_op.drop_column("stop_price")
        batch_op.drop_column("group_id")
        batch_op.drop_column("role")

    with op.batch_alter_table("round_trips", schema=None) as batch_op:
        batch_op.drop_index("ix_round_trips_instrument")
    op.drop_table("round_trips")
    op.drop_table("risk_state")

    with op.batch_alter_table("reconciliations", schema=None) as batch_op:
        batch_op.drop_index("ix_reconciliations_class")
    op.drop_table("reconciliations")
    op.drop_table("basket_status")
